name: ADT Release Build

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Install dependencies
        run: sudo apt-get install -y python3-paramiko python3-lxml zip

      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.x

      - name: Restore
        run: dotnet restore

      - name: Build Packaging
        run: dotnet build Content.Packaging --configuration Release --no-restore /m

      - name: Publish Windows Server
        run: dotnet publish Content.Server --configuration Release --runtime win-x64 --self-contained false -o Content.Server/publish

      # - name: Package server (Linux)
      #   run: dotnet run --project Content.Packaging server --platform linux-x64

      - name: Package client
        run: dotnet run --project Content.Packaging client --no-wipe-release

      - name: Package Windows Server
        run: |
          mkdir -p release
          if [ ! -d Content.Server/publish ]; then
            echo "❌ Не удалось найти папку publish"
            exit 1
          fi
          cd Content.Server/publish
          zip -r ../../release/SS14.Server_win-x64.zip .

      - name: Prepare release folder
        run: |
          mkdir -p "release/${{ github.sha }}"
          mv release/*.zip "release/${{ github.sha }}"

      - name: Upload release artifacts
        uses: actions/upload-artifact@v4
        with:
          name: adt-release
          path: release/**/*.zip

  release:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set variables
        id: vars
        run: |
          echo "release_date=$(date +'%Y-%m-%d')" >> $GITHUB_OUTPUT
          echo "branch=${{ github.ref_name }}" >> $GITHUB_OUTPUT

      - name: Download release artifacts
        uses: actions/download-artifact@v4
        with:
          name: adt-release
          path: release

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: "release-${{ steps.vars.outputs.release_date }}"
          name: "Release ${{ steps.vars.outputs.release_date }} from branch ${{ steps.vars.outputs.branch }}"
          body: |
            Автоматический билд от `${{ steps.vars.outputs.release_date }}`
            Ветка: `${{ steps.vars.outputs.branch }}`
            Коммит: `${{ github.sha }}`
          files: release/**/*.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
